package com.gamersrepublic.presentation;
import com.gamersrepublic.config.ConnectionConfig;
import com.gamersrepublic.domain.Employee;
import com.gamersrepublic.domain.Supplier;
import com.gamersrepublic.repository.SupplierRepository;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;



/**
 *
 * @author Wesley
 */

public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    DefaultTableModel model;
    DefaultTableModel model1;
    private static ApplicationContext ctx;
    private Long id;
    private SupplierRepository repo;
    private Employee user;
    
    public MainMenu() {
        initComponents();
        model = (DefaultTableModel) tblInventory.getModel();
        model1 = (DefaultTableModel) tblContacts.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlInventory2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnAddContact = new javax.swing.JButton();
        btnUpdateContact = new javax.swing.JButton();
        btnDeleteContact = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblContacts = new javax.swing.JTable();
        pnlInventory3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtConName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtConAddress = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtConTel = new javax.swing.JTextField();
        txtConCel = new javax.swing.JTextField();
        txtConEmail = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtConWeb = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtConDesc = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        pnlInvManager = new javax.swing.JPanel();
        pnlInventory = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cmboxTypeInput = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        pnlInventory1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbxType = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pnlMainMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 400, 400));
        setForeground(java.awt.Color.black);
        setMinimumSize(new java.awt.Dimension(1025, 730));
        getContentPane().setLayout(null);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setInheritsPopupMenu(true);
        jTabbedPane1.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1263, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Process Order", jPanel3);

        jPanel2.setLayout(null);

        pnlInventory2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Filter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Constantia", 0, 14))); // NOI18N
        pnlInventory2.setToolTipText("Categories");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Functions"));

        btnAddContact.setText("Add");
        btnAddContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddContactActionPerformed(evt);
            }
        });

        btnUpdateContact.setText("Update");
        btnUpdateContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateContactActionPerformed(evt);
            }
        });

        btnDeleteContact.setText("Delete");
        btnDeleteContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteContactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddContact, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnUpdateContact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnDeleteContact, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnAddContact)
                .addComponent(btnUpdateContact)
                .addComponent(btnDeleteContact))
        );

        javax.swing.GroupLayout pnlInventory2Layout = new javax.swing.GroupLayout(pnlInventory2);
        pnlInventory2.setLayout(pnlInventory2Layout);
        pnlInventory2Layout.setHorizontalGroup(
            pnlInventory2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventory2Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 155, Short.MAX_VALUE))
        );
        pnlInventory2Layout.setVerticalGroup(
            pnlInventory2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventory2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );

        jPanel2.add(pnlInventory2);
        pnlInventory2.setBounds(120, 60, 790, 120);

        tblContacts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"CNA", "0217654312", "086578453", "cna@gmail.co.za", "12 Crescent Road", "www.cna.co.za", "Stationary Equiptment"}
            },
            new String [] {
                "Name", "Telephone", "Cellphone", "Email", "Address", "Website", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblContacts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContactsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblContacts);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(120, 200, 790, 170);

        pnlInventory3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Constantia", 0, 14))); // NOI18N
        pnlInventory3.setToolTipText("Categories");
        pnlInventory3.setName("pnlEdit"); // NOI18N

        jLabel15.setText("Cellphone");

        jLabel16.setText("Name");

        jLabel17.setText("Email");

        jLabel18.setText("Telephone");

        jLabel19.setText("Address");

        jLabel20.setText("Website");

        jLabel21.setText("Description");

        txtConDesc.setColumns(20);
        txtConDesc.setRows(5);
        jScrollPane4.setViewportView(txtConDesc);

        javax.swing.GroupLayout pnlInventory3Layout = new javax.swing.GroupLayout(pnlInventory3);
        pnlInventory3.setLayout(pnlInventory3Layout);
        pnlInventory3Layout.setHorizontalGroup(
            pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventory3Layout.createSequentialGroup()
                .addGroup(pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlInventory3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConCel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtConWeb, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                    .addGroup(pnlInventory3Layout.createSequentialGroup()
                        .addGroup(pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInventory3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtConName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInventory3Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtConTel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtConEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(txtConAddress))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInventory3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 235, Short.MAX_VALUE))
                    .addGroup(pnlInventory3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnlInventory3Layout.setVerticalGroup(
            pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventory3Layout.createSequentialGroup()
                .addGroup(pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInventory3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInventory3Layout.createSequentialGroup()
                        .addGroup(pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtConName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(txtConEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtConTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(txtConAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtConCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(txtConWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        jPanel2.add(pnlInventory3);
        pnlInventory3.setBounds(120, 400, 790, 180);
        jPanel2.add(jLabel13);
        jLabel13.setBounds(0, 0, 1010, 0);

        jTabbedPane1.addTab("My Contacts", jPanel2);

        pnlInvManager.setLayout(null);

        pnlInventory.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Constantia", 0, 14))); // NOI18N
        pnlInventory.setToolTipText("Categories");
        pnlInventory.setName("pnlEdit"); // NOI18N

        jLabel6.setText("Type:");

        cmboxTypeInput.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Paper", "Decorations", "Ink" }));

        jLabel8.setText("Description:");

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane2.setViewportView(txtDesc);

        jLabel9.setText("Size/Length");

        jLabel10.setText("Price:");

        jLabel11.setText("Quantity:");

        javax.swing.GroupLayout pnlInventoryLayout = new javax.swing.GroupLayout(pnlInventory);
        pnlInventory.setLayout(pnlInventoryLayout);
        pnlInventoryLayout.setHorizontalGroup(
            pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventoryLayout.createSequentialGroup()
                .addGroup(pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInventoryLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cmboxTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInventoryLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlInventoryLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInventoryLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addGap(0, 88, Short.MAX_VALUE))
        );
        pnlInventoryLayout.setVerticalGroup(
            pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventoryLayout.createSequentialGroup()
                .addGroup(pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmboxTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pnlInvManager.add(pnlInventory);
        pnlInventory.setBounds(150, 440, 700, 180);

        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Description", "Size/Length", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblInventory.setName("tblInventory"); // NOI18N
        tblInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInventoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInventory);

        pnlInvManager.add(jScrollPane1);
        jScrollPane1.setBounds(150, 200, 700, 210);

        pnlInventory1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Filter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Constantia", 0, 14))); // NOI18N
        pnlInventory1.setToolTipText("Categories");

        jLabel7.setText("Type");

        cmbxType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Paper", "Decorations", "Ink" }));
        cmbxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxTypeActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Functions"));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnAdd)
                .addComponent(btnUpdate)
                .addComponent(btnDelete))
        );

        javax.swing.GroupLayout pnlInventory1Layout = new javax.swing.GroupLayout(pnlInventory1);
        pnlInventory1.setLayout(pnlInventory1Layout);
        pnlInventory1Layout.setHorizontalGroup(
            pnlInventory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventory1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
        );
        pnlInventory1Layout.setVerticalGroup(
            pnlInventory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventory1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInventory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(pnlInventory1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );

        pnlInvManager.add(pnlInventory1);
        pnlInventory1.setBounds(150, 50, 700, 120);

        jLabel5.setText("Inventory");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        pnlInvManager.add(jLabel5);
        jLabel5.setBounds(0, 210, 810, 330);

        jTabbedPane1.addTab("Inventory Manager", pnlInvManager);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1263, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Help", jPanel4);

        pnlMainMenu.setLayout(null);
        pnlMainMenu.add(jLabel1);
        jLabel1.setBounds(-10, 300, 750, 250);

        jTabbedPane1.addTab("Main Menu", pnlMainMenu);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 80, 1270, 660);

        jPanel6.setBackground(new java.awt.Color(168, 190, 236));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setOpaque(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1248, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(20, 10, 1250, 60);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        jLabel4.setText("Business Management System");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(380, -20, 550, 120);

        setSize(new java.awt.Dimension(1288, 772));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxTypeActionPerformed
        // TODO add your handling code here:
        if(cmbxType.getSelectedIndex()==1)
        {
            
              model.insertRow(model.getRowCount(), new Object[]{"Paper", "Plain", "A4",  new Float(12.5),  new Integer(15)});
    
        }
        
        if(cmbxType.getSelectedIndex()==2)
        {
            
             model.insertRow(model.getRowCount(), new Object[] {"Decorations", "Silk", "3m",  new Float(50.0),  new Integer(10)});
            
        }
        
            if(cmbxType.getSelectedIndex()==3)
        {
             model.insertRow(model.getRowCount(), new Object[]  {"Ink", "Colour", "50ml",  new Float(250.0),  new Integer(2)});
       
        }
    }//GEN-LAST:event_cmbxTypeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model1 = (DefaultTableModel) tblInventory.getModel();
        model1.addRow(new Object[]{cmboxTypeInput.getSelectedItem().toString(), txtDesc.getText(), txtSize.getText(), txtPrice.getText(),txtQuantity.getText() });
       
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventoryMouseClicked
        // TODO add your handling code here:
        if(String.valueOf(model.getValueAt(tblInventory.getSelectedRow() , 0)) == "Paper")
        {
            cmboxTypeInput.setSelectedIndex(0);
        }
        else if(String.valueOf(model.getValueAt(tblInventory.getSelectedRow() , 0)) == "Decorations")
        {
            cmboxTypeInput.setSelectedIndex(1);
        }
        else if(String.valueOf(model.getValueAt(tblInventory.getSelectedRow() , 0)) == "Ink")
        {
            cmboxTypeInput.setSelectedIndex(2);
        }
        
        txtDesc.setText(String.valueOf(model.getValueAt(tblInventory.getSelectedRow() , 1)));
        txtSize.setText(String.valueOf(model.getValueAt(tblInventory.getSelectedRow() , 2)));
        txtPrice.setText(String.valueOf(model.getValueAt(tblInventory.getSelectedRow() , 3)));
        txtQuantity.setText(String.valueOf(model.getValueAt(tblInventory.getSelectedRow() , 4)));
    }//GEN-LAST:event_tblInventoryMouseClicked

    String Type;
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        ;
        if(String.valueOf(model.getValueAt(tblInventory.getSelectedRow() , 0)) == "Paper")
        {
            Type = "Paper";
        }
        else if(String.valueOf(model.getValueAt(tblInventory.getSelectedRow() , 0)) == "Decorations")
        {
            Type = "Decorations";
        }
        else if(String.valueOf(model.getValueAt(tblInventory.getSelectedRow() , 0)) == "Ink")
        {
            Type = "Ink";
        }
        //Testing purposes
        //JOptionPane.showMessageDialog(null, Type);
        model.setValueAt(Type, tblInventory.getSelectedRow(),0);
        model.setValueAt(txtDesc.getText(), tblInventory.getSelectedRow(),1);
        model.setValueAt(txtSize.getText(), tblInventory.getSelectedRow(),2);
        model.setValueAt(txtPrice.getText(), tblInventory.getSelectedRow(),3);
        model.setValueAt(txtQuantity.getText(), tblInventory.getSelectedRow(),4);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        model.removeRow(tblInventory.getSelectedRow());
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddContactActionPerformed
        // TODO add your handling code here:
        /*
        repo = ctx.getBean(SupplierRepository.class);
        String name = txtConName.getText();
        String tel = txtConTel.getText();
        String cel = txtConCel.getText();
        String addr = txtConAddress.getText();
        String web = txtConWeb.getText();
        String emailAd = txtConEmail.getText();
        
        Supplier supplier = new Supplier.Builder(name)
                .address(addr)
                .contactCellphone(cel)
                .emailAddress(emailAd)
                .contactLandline(tel)
                .websiteURL(web)
                .build();
        
        repo.save(supplier);
*/
        DefaultTableModel model1 = (DefaultTableModel) tblContacts.getModel();
        model1.addRow(new Object[]{txtConName.getText(), txtConTel.getText(), txtConCel.getText(), txtConEmail.getText(),txtConAddress.getText(),txtConWeb.getText(),txtConDesc.getText() });
    }//GEN-LAST:event_btnAddContactActionPerformed

    private void btnUpdateContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateContactActionPerformed

    private void btnDeleteContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteContactActionPerformed
        // TODO add your handling code here:
         int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this item?", "Confirm",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);       

         
        if(response==0)
        {
         model1.removeRow(tblContacts.getSelectedRow());
         JOptionPane.showMessageDialog(null,"Record Succesfully Deleted");
        }
        else 
        {
            return;
        }
    }//GEN-LAST:event_btnDeleteContactActionPerformed

    private void tblContactsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContactsMouseClicked
        // TODO add your handling code here:
        txtConName.setText(String.valueOf(model1.getValueAt(tblContacts.getSelectedRow() , 0)));
        txtConTel.setText(String.valueOf(model1.getValueAt(tblContacts.getSelectedRow() , 1)));
        txtConCel.setText(String.valueOf(model1.getValueAt(tblContacts.getSelectedRow() , 2)));
        txtConEmail.setText(String.valueOf(model1.getValueAt(tblContacts.getSelectedRow() , 3)));
        txtConAddress.setText(String.valueOf(model1.getValueAt(tblContacts.getSelectedRow() , 4)));
        txtConWeb.setText(String.valueOf(model1.getValueAt(tblContacts.getSelectedRow() , 5)));
        txtConDesc.setText(String.valueOf(model1.getValueAt(tblContacts.getSelectedRow() , 6)));
    }//GEN-LAST:event_tblContactsMouseClicked
    
    public void setUser(Employee user){
        this.user = user;
    }
    /*
    @BeforeClass
    public static void setUpClass() throws Exception {
        ctx = new AnnotationConfigApplicationContext(ConnectionConfig.class);
    }*/
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddContact;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteContact;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateContact;
    private javax.swing.JComboBox cmboxTypeInput;
    private javax.swing.JComboBox cmbxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlInvManager;
    private javax.swing.JPanel pnlInventory;
    private javax.swing.JPanel pnlInventory1;
    private javax.swing.JPanel pnlInventory2;
    private javax.swing.JPanel pnlInventory3;
    private javax.swing.JPanel pnlMainMenu;
    private javax.swing.JTable tblContacts;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTextField txtConAddress;
    private javax.swing.JTextField txtConCel;
    private javax.swing.JTextArea txtConDesc;
    private javax.swing.JTextField txtConEmail;
    private javax.swing.JTextField txtConName;
    private javax.swing.JTextField txtConTel;
    private javax.swing.JTextField txtConWeb;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSize;
    // End of variables declaration//GEN-END:variables
}
