package com.gamersrepublic.presentation;
import com.gamersrepublic.config.ConnectionConfig;
import com.gamersrepublic.domain.Employee;
import com.gamersrepublic.domain.Supplier;
import com.gamersrepublic.repository.SupplierRepository;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;



/**
 *
 * @author Wesley
 */

public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    DefaultTableModel model;
    DefaultTableModel model1;
    private static ApplicationContext ctx;
    private Long id;
    private SupplierRepository repo;
    private Employee user;
    
    public MainMenu() {
        initComponents();
        model = (DefaultTableModel) tblInventory.getModel();
        model1 = (DefaultTableModel) tblContacts.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlMainMenu = new javax.swing.JPanel();
        lblInvetoryLevels = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        lblMain = new javax.swing.JLabel();
        lblInvetoryLevels3 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblInventoryLevels1 = new javax.swing.JTable();
        lblInvetoryLevels1 = new javax.swing.JLabel();
        lblInvetoryLevels4 = new javax.swing.JLabel();
        pnlProcessOrder = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtOrderNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtOrderDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtOrderDueDate = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblInventory1 = new javax.swing.JTable();
        btnProcessOrder = new javax.swing.JButton();
        lblInvetoryLevels5 = new javax.swing.JLabel();
        pnlInvManager = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlInventory1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbxType = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        pnlInventory = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cmboxTypeInput = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblInvetoryLevels6 = new javax.swing.JLabel();
        pnlContacts = new javax.swing.JPanel();
        pnlInventory2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnAddContact = new javax.swing.JButton();
        btnUpdateContact = new javax.swing.JButton();
        btnDeleteContact = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblContacts = new javax.swing.JTable();
        pnlInventory3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtConName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtConAddress = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtConTel = new javax.swing.JTextField();
        txtConCel = new javax.swing.JTextField();
        txtConEmail = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtConWeb = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtConDesc = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        lblInvetoryLevels7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblInvetoryLevels2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(190, 213, 213));
        setBounds(new java.awt.Rectangle(0, 0, 400, 400));
        setForeground(java.awt.Color.black);
        setMinimumSize(new java.awt.Dimension(1025, 730));
        setResizable(false);
        getContentPane().setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(95, 136, 177));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jTabbedPane1.setInheritsPopupMenu(true);
        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.setOpaque(true);

        pnlMainMenu.setLayout(null);

        lblInvetoryLevels.setBackground(new java.awt.Color(95, 136, 177));
        lblInvetoryLevels.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lblInvetoryLevels.setForeground(new java.awt.Color(255, 255, 255));
        lblInvetoryLevels.setOpaque(true);
        pnlMainMenu.add(lblInvetoryLevels);
        lblInvetoryLevels.setBounds(0, 0, 1020, 10);
        pnlMainMenu.add(canvas1);
        canvas1.setBounds(730, 150, 0, 0);

        lblMain.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gamersrepublic/presentation/Welcome-Home-Request-Invitation.jpg"))); // NOI18N
        lblMain.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        pnlMainMenu.add(lblMain);
        lblMain.setBounds(0, 10, 1010, 40);

        lblInvetoryLevels3.setBackground(new java.awt.Color(95, 136, 177));
        lblInvetoryLevels3.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lblInvetoryLevels3.setForeground(new java.awt.Color(255, 255, 255));
        lblInvetoryLevels3.setText("                   Welcome back user!");
        lblInvetoryLevels3.setOpaque(true);
        pnlMainMenu.add(lblInvetoryLevels3);
        lblInvetoryLevels3.setBounds(330, 50, 320, 20);

        jScrollPane8.setAutoscrolls(true);

        tblInventoryLevels1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Paper",  new Double(100.0)},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Item", "Inventory"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tblInventoryLevels1);
        if (tblInventoryLevels1.getColumnModel().getColumnCount() > 0) {
            tblInventoryLevels1.getColumnModel().getColumn(0).setResizable(false);
            tblInventoryLevels1.getColumnModel().getColumn(1).setResizable(false);
        }

        pnlMainMenu.add(jScrollPane8);
        jScrollPane8.setBounds(10, 130, 320, 90);

        lblInvetoryLevels1.setBackground(new java.awt.Color(95, 136, 177));
        lblInvetoryLevels1.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lblInvetoryLevels1.setForeground(new java.awt.Color(255, 255, 255));
        lblInvetoryLevels1.setText("                   Upcoming Orders");
        lblInvetoryLevels1.setOpaque(true);
        pnlMainMenu.add(lblInvetoryLevels1);
        lblInvetoryLevels1.setBounds(680, 100, 297, 31);

        lblInvetoryLevels4.setBackground(new java.awt.Color(95, 136, 177));
        lblInvetoryLevels4.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lblInvetoryLevels4.setForeground(new java.awt.Color(255, 255, 255));
        lblInvetoryLevels4.setText("                       Inventory Levels");
        lblInvetoryLevels4.setOpaque(true);
        pnlMainMenu.add(lblInvetoryLevels4);
        lblInvetoryLevels4.setBounds(10, 100, 320, 30);

        jTabbedPane1.addTab("Home", pnlMainMenu);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Constantia", 0, 14))); // NOI18N

        jLabel2.setText("Order No:");

        txtOrderNo.setText("jTextField1");

        jLabel3.setText("Order Date:");

        txtOrderDate.setText("jTextField1");

        jLabel5.setText("Order Due Date:");

        txtOrderDueDate.setText("jTextField1");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order Items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Constantia", 0, 14))); // NOI18N

        tblInventory1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Description", "Size/Length", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblInventory1.setName("tblInventory"); // NOI18N
        tblInventory1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInventory1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblInventory1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        btnProcessOrder.setText("Process Order");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnProcessOrder)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtOrderDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtOrderDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnProcessOrder)
                .addGap(23, 23, 23))
        );

        lblInvetoryLevels5.setBackground(new java.awt.Color(95, 136, 177));
        lblInvetoryLevels5.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lblInvetoryLevels5.setForeground(new java.awt.Color(255, 255, 255));
        lblInvetoryLevels5.setOpaque(true);

        javax.swing.GroupLayout pnlProcessOrderLayout = new javax.swing.GroupLayout(pnlProcessOrder);
        pnlProcessOrder.setLayout(pnlProcessOrderLayout);
        pnlProcessOrderLayout.setHorizontalGroup(
            pnlProcessOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProcessOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(pnlProcessOrderLayout.createSequentialGroup()
                .addComponent(lblInvetoryLevels5, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlProcessOrderLayout.setVerticalGroup(
            pnlProcessOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProcessOrderLayout.createSequentialGroup()
                .addComponent(lblInvetoryLevels5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Process Order", pnlProcessOrder);

        pnlInvManager.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnlInventory1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Filter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Constantia", 0, 14))); // NOI18N
        pnlInventory1.setToolTipText("Categories");

        jLabel7.setText("Type");

        cmbxType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Paper", "Decorations", "Ink" }));
        cmbxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxTypeActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Functions"));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnAdd)
                .addComponent(btnUpdate)
                .addComponent(btnDelete))
        );

        javax.swing.GroupLayout pnlInventory1Layout = new javax.swing.GroupLayout(pnlInventory1);
        pnlInventory1.setLayout(pnlInventory1Layout);
        pnlInventory1Layout.setHorizontalGroup(
            pnlInventory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventory1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
        );
        pnlInventory1Layout.setVerticalGroup(
            pnlInventory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventory1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInventory1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlInventory1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );

        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Description", "Size/Length", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblInventory.setName("tblInventory"); // NOI18N
        tblInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInventoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInventory);

        pnlInventory.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Constantia", 0, 14))); // NOI18N
        pnlInventory.setToolTipText("Categories");
        pnlInventory.setName("pnlEdit"); // NOI18N

        jLabel6.setText("Type:");

        cmboxTypeInput.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Paper", "Decorations", "Ink" }));

        jLabel8.setText("Description:");

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane2.setViewportView(txtDesc);

        jLabel9.setText("Size/Length");

        jLabel10.setText("Price:");

        jLabel11.setText("Quantity:");

        javax.swing.GroupLayout pnlInventoryLayout = new javax.swing.GroupLayout(pnlInventory);
        pnlInventory.setLayout(pnlInventoryLayout);
        pnlInventoryLayout.setHorizontalGroup(
            pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventoryLayout.createSequentialGroup()
                .addGroup(pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInventoryLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cmboxTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInventoryLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlInventoryLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInventoryLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlInventoryLayout.setVerticalGroup(
            pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventoryLayout.createSequentialGroup()
                .addGroup(pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmboxTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInventoryLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addContainerGap(75, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInventoryLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlInventory1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(67, 67, 67))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(pnlInventory1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(pnlInventory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pnlInvManager.add(jPanel2);
        jPanel2.setBounds(0, 20, 920, 580);

        lblInvetoryLevels6.setBackground(new java.awt.Color(95, 136, 177));
        lblInvetoryLevels6.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lblInvetoryLevels6.setForeground(new java.awt.Color(255, 255, 255));
        lblInvetoryLevels6.setOpaque(true);
        pnlInvManager.add(lblInvetoryLevels6);
        lblInvetoryLevels6.setBounds(0, 0, 1020, 10);

        jTabbedPane1.addTab("Inventory Manager", pnlInvManager);

        pnlContacts.setLayout(null);

        pnlInventory2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Filter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Constantia", 0, 14))); // NOI18N
        pnlInventory2.setToolTipText("Categories");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Functions"));

        btnAddContact.setText("Add");
        btnAddContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddContactActionPerformed(evt);
            }
        });

        btnUpdateContact.setText("Update");
        btnUpdateContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateContactActionPerformed(evt);
            }
        });

        btnDeleteContact.setText("Delete");
        btnDeleteContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteContactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddContact, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnUpdateContact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnDeleteContact, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnAddContact)
                .addComponent(btnUpdateContact)
                .addComponent(btnDeleteContact))
        );

        javax.swing.GroupLayout pnlInventory2Layout = new javax.swing.GroupLayout(pnlInventory2);
        pnlInventory2.setLayout(pnlInventory2Layout);
        pnlInventory2Layout.setHorizontalGroup(
            pnlInventory2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventory2Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 155, Short.MAX_VALUE))
        );
        pnlInventory2Layout.setVerticalGroup(
            pnlInventory2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventory2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );

        pnlContacts.add(pnlInventory2);
        pnlInventory2.setBounds(90, 20, 790, 120);

        tblContacts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"CNA", "0217654312", "086578453", "cna@gmail.co.za", "12 Crescent Road", "www.cna.co.za", "Stationary Equiptment"}
            },
            new String [] {
                "Name", "Telephone", "Cellphone", "Email", "Address", "Website", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblContacts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContactsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblContacts);

        pnlContacts.add(jScrollPane3);
        jScrollPane3.setBounds(90, 160, 790, 170);

        pnlInventory3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Constantia", 0, 14))); // NOI18N
        pnlInventory3.setToolTipText("Categories");
        pnlInventory3.setName("pnlEdit"); // NOI18N

        jLabel15.setText("Cellphone");

        jLabel16.setText("Name");

        jLabel17.setText("Email");

        jLabel18.setText("Telephone");

        jLabel19.setText("Address");

        jLabel20.setText("Website");

        jLabel21.setText("Description");

        txtConDesc.setColumns(20);
        txtConDesc.setRows(5);
        jScrollPane4.setViewportView(txtConDesc);

        javax.swing.GroupLayout pnlInventory3Layout = new javax.swing.GroupLayout(pnlInventory3);
        pnlInventory3.setLayout(pnlInventory3Layout);
        pnlInventory3Layout.setHorizontalGroup(
            pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventory3Layout.createSequentialGroup()
                .addGroup(pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlInventory3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConCel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtConWeb, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                    .addGroup(pnlInventory3Layout.createSequentialGroup()
                        .addGroup(pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInventory3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtConName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInventory3Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtConTel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtConEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(txtConAddress))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInventory3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 235, Short.MAX_VALUE))
                    .addGroup(pnlInventory3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnlInventory3Layout.setVerticalGroup(
            pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventory3Layout.createSequentialGroup()
                .addGroup(pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInventory3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInventory3Layout.createSequentialGroup()
                        .addGroup(pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtConName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(txtConEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtConTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(txtConAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(pnlInventory3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtConCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(txtConWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        pnlContacts.add(pnlInventory3);
        pnlInventory3.setBounds(90, 340, 790, 180);
        pnlContacts.add(jLabel13);
        jLabel13.setBounds(0, 0, 1010, 0);

        lblInvetoryLevels7.setBackground(new java.awt.Color(95, 136, 177));
        lblInvetoryLevels7.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lblInvetoryLevels7.setForeground(new java.awt.Color(255, 255, 255));
        lblInvetoryLevels7.setOpaque(true);
        pnlContacts.add(lblInvetoryLevels7);
        lblInvetoryLevels7.setBounds(0, 0, 1020, 10);

        jTabbedPane1.addTab("My Contacts", pnlContacts);

        lblInvetoryLevels2.setBackground(new java.awt.Color(95, 136, 177));
        lblInvetoryLevels2.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lblInvetoryLevels2.setForeground(new java.awt.Color(255, 255, 255));
        lblInvetoryLevels2.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lblInvetoryLevels2, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lblInvetoryLevels2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 619, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Help", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 70, 1030, 670);
        jTabbedPane1.getAccessibleContext().setAccessibleName("Home");

        jPanel8.setBackground(new java.awt.Color(95, 136, 177));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Business Management System");

        jLabel4.setBackground(new java.awt.Color(203, 205, 221));
        jLabel4.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        jLabel4.setText("[USER] is logged in");
        jLabel4.setOpaque(true);

        jButton1.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        jButton1.setLabel("Logout?");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jLabel4.getAccessibleContext().setAccessibleName("lblUserLoggedIn");
        jLabel4.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanel8);
        jPanel8.setBounds(0, -10, 1020, 80);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9);
        jPanel9.setBounds(420, 30, 100, 60);

        setSize(new java.awt.Dimension(999, 756));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxTypeActionPerformed
        // TODO add your handling code here:
        if(cmbxType.getSelectedIndex()==1)
        {
            
              model.insertRow(model.getRowCount(), new Object[]{"Paper", "Plain", "A4",  new Float(12.5),  new Integer(15)});
    
        }
        
        if(cmbxType.getSelectedIndex()==2)
        {
            
             model.insertRow(model.getRowCount(), new Object[] {"Decorations", "Silk", "3m",  new Float(50.0),  new Integer(10)});
            
        }
        
            if(cmbxType.getSelectedIndex()==3)
        {
             model.insertRow(model.getRowCount(), new Object[]  {"Ink", "Colour", "50ml",  new Float(250.0),  new Integer(2)});
       
        }
    }//GEN-LAST:event_cmbxTypeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model1 = (DefaultTableModel) tblInventory.getModel();
        model1.addRow(new Object[]{cmboxTypeInput.getSelectedItem().toString(), txtDesc.getText(), txtSize.getText(), txtPrice.getText(),txtQuantity.getText() });
       
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventoryMouseClicked
        // TODO add your handling code here:
        if(String.valueOf(model.getValueAt(tblInventory.getSelectedRow() , 0)) == "Paper")
        {
            cmboxTypeInput.setSelectedIndex(0);
        }
        else if(String.valueOf(model.getValueAt(tblInventory.getSelectedRow() , 0)) == "Decorations")
        {
            cmboxTypeInput.setSelectedIndex(1);
        }
        else if(String.valueOf(model.getValueAt(tblInventory.getSelectedRow() , 0)) == "Ink")
        {
            cmboxTypeInput.setSelectedIndex(2);
        }
        
        txtDesc.setText(String.valueOf(model.getValueAt(tblInventory.getSelectedRow() , 1)));
        txtSize.setText(String.valueOf(model.getValueAt(tblInventory.getSelectedRow() , 2)));
        txtPrice.setText(String.valueOf(model.getValueAt(tblInventory.getSelectedRow() , 3)));
        txtQuantity.setText(String.valueOf(model.getValueAt(tblInventory.getSelectedRow() , 4)));
    }//GEN-LAST:event_tblInventoryMouseClicked

    String Type;
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        ;
        if(String.valueOf(model.getValueAt(tblInventory.getSelectedRow() , 0)) == "Paper")
        {
            Type = "Paper";
        }
        else if(String.valueOf(model.getValueAt(tblInventory.getSelectedRow() , 0)) == "Decorations")
        {
            Type = "Decorations";
        }
        else if(String.valueOf(model.getValueAt(tblInventory.getSelectedRow() , 0)) == "Ink")
        {
            Type = "Ink";
        }
        //Testing purposes
        //JOptionPane.showMessageDialog(null, Type);
        model.setValueAt(Type, tblInventory.getSelectedRow(),0);
        model.setValueAt(txtDesc.getText(), tblInventory.getSelectedRow(),1);
        model.setValueAt(txtSize.getText(), tblInventory.getSelectedRow(),2);
        model.setValueAt(txtPrice.getText(), tblInventory.getSelectedRow(),3);
        model.setValueAt(txtQuantity.getText(), tblInventory.getSelectedRow(),4);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this item?", "Confirm",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);       

         
        if(response==0)
        {
         model.removeRow(tblInventory.getSelectedRow());
         JOptionPane.showMessageDialog(null,"Record Succesfully Deleted");
        }
        else 
        {
            return;
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddContactActionPerformed
        // TODO add your handling code here:
        /*
        repo = ctx.getBean(SupplierRepository.class);
        String name = txtConName.getText();
        String tel = txtConTel.getText();
        String cel = txtConCel.getText();
        String addr = txtConAddress.getText();
        String web = txtConWeb.getText();
        String emailAd = txtConEmail.getText();
        
        Supplier supplier = new Supplier.Builder(name)
                .address(addr)
                .contactCellphone(cel)
                .emailAddress(emailAd)
                .contactLandline(tel)
                .websiteURL(web)
                .build();
        
        repo.save(supplier);
*/
        DefaultTableModel model1 = (DefaultTableModel) tblContacts.getModel();
        model1.addRow(new Object[]{txtConName.getText(), txtConTel.getText(), txtConCel.getText(), txtConEmail.getText(),txtConAddress.getText(),txtConWeb.getText(),txtConDesc.getText() });
    }//GEN-LAST:event_btnAddContactActionPerformed

    private void btnUpdateContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateContactActionPerformed

    private void btnDeleteContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteContactActionPerformed
        // TODO add your handling code here:
         int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this item?", "Confirm",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);       

         
        if(response==0)
        {
         model1.removeRow(tblContacts.getSelectedRow());
         JOptionPane.showMessageDialog(null,"Record Succesfully Deleted");
        }
        else 
        {
            return;
        }
    }//GEN-LAST:event_btnDeleteContactActionPerformed

    private void tblContactsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContactsMouseClicked
        // TODO add your handling code here:
        txtConName.setText(String.valueOf(model1.getValueAt(tblContacts.getSelectedRow() , 0)));
        txtConTel.setText(String.valueOf(model1.getValueAt(tblContacts.getSelectedRow() , 1)));
        txtConCel.setText(String.valueOf(model1.getValueAt(tblContacts.getSelectedRow() , 2)));
        txtConEmail.setText(String.valueOf(model1.getValueAt(tblContacts.getSelectedRow() , 3)));
        txtConAddress.setText(String.valueOf(model1.getValueAt(tblContacts.getSelectedRow() , 4)));
        txtConWeb.setText(String.valueOf(model1.getValueAt(tblContacts.getSelectedRow() , 5)));
        txtConDesc.setText(String.valueOf(model1.getValueAt(tblContacts.getSelectedRow() , 6)));
    }//GEN-LAST:event_tblContactsMouseClicked

    private void tblInventory1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventory1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblInventory1MouseClicked
    
    public void setUser(Employee user){
        this.user = user;
    }
    /*
    @BeforeClass
    public static void setUpClass() throws Exception {
        ctx = new AnnotationConfigApplicationContext(ConnectionConfig.class);
    }*/
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddContact;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteContact;
    private javax.swing.JButton btnProcessOrder;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateContact;
    private javax.swing.ButtonGroup buttonGroup1;
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox cmboxTypeInput;
    private javax.swing.JComboBox cmbxType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblInvetoryLevels;
    private javax.swing.JLabel lblInvetoryLevels1;
    private javax.swing.JLabel lblInvetoryLevels2;
    private javax.swing.JLabel lblInvetoryLevels3;
    private javax.swing.JLabel lblInvetoryLevels4;
    private javax.swing.JLabel lblInvetoryLevels5;
    private javax.swing.JLabel lblInvetoryLevels6;
    private javax.swing.JLabel lblInvetoryLevels7;
    private javax.swing.JLabel lblMain;
    private javax.swing.JPanel pnlContacts;
    private javax.swing.JPanel pnlInvManager;
    private javax.swing.JPanel pnlInventory;
    private javax.swing.JPanel pnlInventory1;
    private javax.swing.JPanel pnlInventory2;
    private javax.swing.JPanel pnlInventory3;
    private javax.swing.JPanel pnlMainMenu;
    private javax.swing.JPanel pnlProcessOrder;
    private javax.swing.JTable tblContacts;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTable tblInventory1;
    private javax.swing.JTable tblInventoryLevels1;
    private javax.swing.JTextField txtConAddress;
    private javax.swing.JTextField txtConCel;
    private javax.swing.JTextArea txtConDesc;
    private javax.swing.JTextField txtConEmail;
    private javax.swing.JTextField txtConName;
    private javax.swing.JTextField txtConTel;
    private javax.swing.JTextField txtConWeb;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtOrderDate;
    private javax.swing.JTextField txtOrderDueDate;
    private javax.swing.JTextField txtOrderNo;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSize;
    // End of variables declaration//GEN-END:variables
}
